# Copyright (C) 2018 UCSC Computational Genomics Lab
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Launch Azure VM
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    dnsname: '{{ vmname }}.westus.cloudapp.azure.com'
    # The DNS name might not be right depending on your region!!
    ip: "{{ lookup ('dig', '{{ dnsname }}') }}"

  tasks:
  - debug: msg="Public DNS name {{ dnsname }} resolved to IP {{ ip }}."
# The following check is disabled so that the playbook does not stop upon existence of DNS name. Otherwise
# it cannot be re-run after VM creation
#  - name: Check if DNS is taken
#    fail: msg="That DNS name seems to be already taken"
#    when: ip != 'NXDOMAIN'

  # TODO: Authentication error when making new resource groups
  - name: Create a resource group
    tags:
      - leader
    # We use resource groups to identify all instances in a cluster.
    azure_rm_resourcegroup:
      name: "{{ resgrp }}"
      location: "{{ region }}"
      state: present

  - name: Create security group that allows SSH and HTTP
    tags:
      - leader
    # All instances in a security group can communicate with each other by default,
    # so we don't have to touch that. All we have to do is open port 22 for SSH.
    azure_rm_securitygroup:
      resource_group: "{{ resgrp }}"
      name: "{{ resgrp }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound

  - name: Create a virtual network
    tags:
      - leader
    # We don't need to run the above two steps if we're adding worker nodes.
    azure_rm_virtualnetwork:
      name: "{{ resgrp }}"
      resource_group: '{{ resgrp }}'
      address_prefixes: '192.168.0.0/16'
      state: present

  - name: Create a subnet
    tags:
      - leader
    azure_rm_subnet:
      name: "{{ vmname }}"
      virtual_network_name: "{{ resgrp }}"
      resource_group: "{{ resgrp }}"
      address_prefix: "192.168.0.0/24"
      security_group_name: "{{ resgrp }}"
      state: present

  - name: Create VM
    # We let Ansible take care of setting up details eg the NIC, public IP,
    # storage account, etc. so we don't need to deal with different naming
    # conventions and all that jazz.
    azure_rm_virtualmachine:
      resource_group: "{{ resgrp }}"
      name: "{{ vmname }}"
      vm_size: "{{ vmsize }}"
      virtual_network_name: "{{ resgrp }}"
      admin_username: core
      ssh_password_enabled: false
      public_ip_allocation_method: Static
      tags:
        role: "{{ role }}"
      image:
        offer: CoreOS
        publisher: CoreOS
        sku: Stable
        # This is close to - but not exactly - the CoreOS version used by the AWS AMI.
        version: 1235.5.0
      ssh_public_keys:
        - { path: "/home/core/.ssh/authorized_keys", key_data: "{{ lookup('file', '{{ keyname }}') }}"}

  - name: Add VM IP to inventory
    # Add the public IP of the VM we just spun up to the inventory so we can finish setting things up
    # Normally, we would just pass the cloud-config file to Azure at VM spin-up time through the custom_data
    # parameter, but Ansible doesn't support that yet.
    # One consequence of this approach is that ssh configuration in the cloud-config file needs to be handled by
    # Ansible, or else bad things happen.
    add_host:
      name: "{{ azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
      groups: new

- name: Post-config
  hosts: new
  remote_user: core
  connection: ssh
  gather_facts: false
  tasks:
  # CoreOS doesn't have Python installed by default, and Ansible doesn't yet support
  # the custom_data parameter, so we need to manually copy the cloud-config file to the new instance.
  # To do this, we run the command from the local/host machine
  - name: Copy cloud-config file to the new instance
    local_action: command scp -o User=core -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no {{ cloudconfig }} {{ inventory_hostname }}:/home/core/userdata

  # Once the file is on the host, we need to put it where it belongs. This needs to be a separate
  # step because scp alone can't transfer files where destination privilege escalation is
  # required. (At least, to my research.)
  # Pretty messy, but this is really just a monkey patch until ansible/ansible#25924 is merged.
  - name: Enable cloud-config file on instance (privileged)
    local_action: command ssh -o User=core -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no {{ inventory_hostname }} "sudo cp /home/core/userdata /var/lib/waagent/CustomData"

# Once all that is done, all we have to do is reboot the instance so that CoreOS
# detects the new cloud-config file.
- name: Post-post-config
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Restart the instance
    azure_rm_virtualmachine:
      name: "{{ vmname }}"
      resource_group: "{{ resgrp }}"
      restarted: true
      state: present
